#!/usr/bin/env python3
"""Regenerate openkruise/agents/models/__init__.py for the Python SDK.

Scans every generated model module, locates the CRD root class (the only
top-level class carrying apiVersion + metadata fields) and re-exports it
along with all other top-level classes under a Kind-prefixed alias, e.g.
"Spec as PoolAutoscalerSpec".

Classes with a numeric suffix (Status1, AuditItem1, Header2 ...) are
datamodel-codegen de-duplication artifacts and are skipped; they remain
importable from their source module directly.

Usage:
    python3 generate_python_init.py <models_dir>
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

NUMBERED_CLASS = re.compile(r"\d+$")

HEADER = "# Code generated by hack/generate_python_sdk.sh. DO NOT EDIT."


def top_level_classes(path: Path) -> list[tuple[str, set[str]]]:
    """Return [(class_name, annotated_field_names)] for every top-level class."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    classes: list[tuple[str, set[str]]] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            fields = {
                stmt.target.id
                for stmt in node.body
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)
            }
            classes.append((node.name, fields))
    return classes


def find_root_class(classes: list[tuple[str, set[str]]]) -> str | None:
    """The CRD root object is the class that carries apiVersion + metadata."""
    for name, fields in classes:
        if "apiVersion" in fields and "metadata" in fields:
            return name
    return None


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <models_dir>", file=sys.stderr)
        sys.exit(1)

    models_dir = Path(sys.argv[1])
    if not models_dir.is_dir():
        print(f"ERROR: Directory not found: {models_dir}", file=sys.stderr)
        sys.exit(1)

    blocks: list[str] = []
    for py_file in sorted(models_dir.glob("*.py")):
        if py_file.name == "__init__.py":
            continue

        classes = top_level_classes(py_file)
        root = find_root_class(classes)
        if root is None:
            print(f"  WARN: no CRD root class in {py_file.name}, skipping", file=sys.stderr)
            continue

        lines = [f"from .{py_file.stem} import (", f"    {root},"]
        for name, _ in sorted(classes):
            if name == root or NUMBERED_CLASS.search(name):
                continue
            lines.append(f"    {name} as {root}{name},")
        lines.append(")")
        blocks.append("\n".join(lines))

    content = f"{HEADER}\n\n" + "\n\n".join(blocks) + "\n"
    init_path = models_dir / "__init__.py"
    # newline="\n" keeps LF line endings on every platform
    with open(init_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    print(f"  Generated {init_path} ({len(blocks)} modules)")


if __name__ == "__main__":
    main()
