# generated by datamodel-codegen:
#   filename:  checkpoint_schema.json
#   timestamp: 2026-09-03T05:22:22+00:00

from __future__ import annotations

from typing import Any

from kubernetes.client.models import V1ObjectMeta
from pydantic import AwareDatetime, BaseModel, ConfigDict


class Checkpoint(BaseModel):
    """
    Checkpoint is the Schema for the Checkpoints API
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec
    """
    spec defines the desired state of Checkpoint
    """
    status: Status | None = None
    """
    status defines the observed state of Checkpoint
    """


class Spec(BaseModel):
    """
    spec defines the desired state of Checkpoint
    """

    keepRunning: bool | None = None
    """
    KeepRunning indicates whether the pod remains in the Running state after passing the checkpoint.
    Default is true.
    """
    persistentContents: list[str] | None = None
    """
    PersistentContents indicates resume pod with persistent content, Enum: podInfo, memory, filesystem
    """
    podName: str | None = None
    """
    PodName is checkpoint podName.
    """
    sandboxName: str | None = None
    """
    SandboxName is checkpoint sandboxName.
    """
    ttlAfterFinished: str | None = None
    """
    valid format: 30s, 30m, 30d
    """


class Status(BaseModel):
    """
    status defines the observed state of Checkpoint
    """

    checkpointId: str | None = None
    """
    checkpoint-id
    """
    completionTime: AwareDatetime | None = None
    """
    CompletionTime is checkpoint completed time, and phase is Succeeded or Failed.
    """
    message: str | None = None
    """
    message
    """
    observedGeneration: int | None = None
    """
    observedGeneration is the most recent generation observed for this Checkpoint. It corresponds to the
    Checkpoint's generation, which is updated on mutation by the API Server.
    """
    phase: str | None = None
    """
    Checkpoint Phase
    """
    podTemplateDelta: Any | None = None
    """
    PodTemplateDelta stores a Strategic Merge Patch that captures the delta between
    the running Pod at pause time and the base Pod generated from sandbox.spec.template
    """
