# generated by datamodel-codegen:
#   filename:  commit_schema.json
#   timestamp: 2026-09-03T05:22:22+00:00

from __future__ import annotations

from enum import StrEnum

from kubernetes.client.models import V1ObjectMeta
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Commit(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec
    status: Status | None = Field({"phase": "Pending"}, validate_default=True)


class Condition(BaseModel):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """

    lastTransitionTime: AwareDatetime
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
    """
    message: str = Field(..., max_length=32768)
    """
    message is a human readable message indicating details about the transition.
    This may be an empty string.
    """
    observedGeneration: int | None = Field(None, ge=0)
    """
    observedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str = Field(
        ...,
        max_length=1024,
        min_length=1,
        pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
    )
    """
    reason contains a programmatic identifier indicating the reason for the condition's last transition.
    Producers of specific condition types may define expected values and meanings for this field,
    and whether the values are considered a guaranteed API.
    The value should be a CamelCase string.
    This field may not be empty.
    """
    status: Status1
    """
    status of the condition, one of True, False, Unknown.
    """
    type: str = Field(
        ...,
        max_length=316,
        pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
    )
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    """


class Phase(StrEnum):
    Pending = "Pending"
    Running = "Running"
    Succeeded = "Succeeded"
    Failed = "Failed"


class RegistryAuth(BaseModel):
    """
    RegistryAuth specifies credentials for pushing the committed image.
    If nil, the commit will attempt an anonymous push.
    """

    credentials: dict[str, str] | None = None
    """
    Credentials is reserved for future use. Currently has no effect.
    """
    secrets: list[str] | None = None
    """
    Secrets is a list of dockerconfigjson Secret names in the same namespace.
    """


class Spec(BaseModel):
    containerName: str
    image: str
    podName: str
    registryAuth: RegistryAuth | None = None
    """
    RegistryAuth specifies credentials for pushing the committed image.
    If nil, the commit will attempt an anonymous push.
    """
    squashLayer: int | None = 0
    """
    SquashLayer is the max number of writable layers to keep after squashing.
    0 means no squashing. Reserved for future implementation.
    """
    timeoutSeconds: int | None = 0
    """
    TimeoutSeconds is the max duration (in seconds) for the commit job.
    Exceeded jobs are terminated and marked Failed. 0 means no timeout.
    """
    ttl: str | None = None
    """
    TtlAfterFinished is how long the Commit is retained after reaching a terminal phase.
    The controller auto-deletes the Commit once TTL expires. Nil means no auto-deletion.
    """


class Status(BaseModel):
    commitID: str | None = None
    completionTime: AwareDatetime | None = None
    conditions: list[Condition] | None = None
    """
    conditions represent the current state of the Commit resource.
    Each condition has a unique type and reflects the status of a specific aspect of the resource.
    The status of each condition is one of True, False, or Unknown.
    """
    phase: Phase
    startTime: AwareDatetime | None = None


class Status1(StrEnum):
    """
    status of the condition, one of True, False, Unknown.
    """

    True_ = "True"
    False_ = "False"
    Unknown = "Unknown"
