# generated by datamodel-codegen:
#   filename:  globalsecurityprofile_schema.json
#   timestamp: 2026-09-03T05:22:23+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from kubernetes.client.models import V1ObjectMeta
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Action(StrEnum):
    """
    Action determines whether the matching tool call is allowed or denied.
    """

    allow = "allow"
    deny = "deny"


class Actions(BaseModel):
    """
    Actions configures the actions executed when this rule matches.
    """

    audit: list[AuditItem1] | None = None
    """
    Audit lists rule-specific audit actions. A non-empty list replaces the
    profile-level Audit list for this rule. An empty list inherits the
    profile-level list.
    """
    block: Block | None = None
    """
    Block is a terminal action that returns a configured HTTP response
    to the client without forwarding upstream.
    """
    bypass: bool | None = None
    """
    Bypass forwards the request and skips all remaining actions and rules
    across matching profiles. False is equivalent to omission.
    """
    headerManipulation: HeaderManipulation | None = None
    """
    HeaderManipulation sets or removes plaintext request headers.
    Non-terminal. Values are stored verbatim — use TokenTransformation
    for credentials.
    """
    mcpToolPolicy: McpToolPolicy | None = None
    """
    MCPToolPolicy defines inline MCP tool access control rules.
    Non-terminal when the policy allows; terminal (like Block) when
    denied.
    """
    tokenTransformation: TokenTransformation | None = None
    """
    TokenTransformation rewrites request credentials.
    Non-terminal.
    """


class ApiKey(BaseModel):
    """
    ApiKey configures an ApiKey transformation. It is required for ApiKey and
    ignored for AliyunSTS. When targetHeaders is set, targetHeaders and value
    take precedence and when, targetHeader, and valueTemplate are ignored.
    Otherwise, the legacy when, targetHeader, and valueTemplate fields apply
    and value is ignored.

    Examples:

    The following example writes the same rendered token value to two fixed
    request headers:

        apiKey:
          targetHeaders:
            names:
            - authorization
            - x-backend-authorization
          value:
            template: "Bearer {{ .Token }}"

    The following example selects every existing request header whose value
    is the token placeholder and replaces each matched value with the token:

        apiKey:
          targetHeaders:
            cel: |
              request.headers.filter(
                name,
                request.headers[name] == "${AGENTIO_TOKEN}"
              )
          value:
            template: "{{ .Token }}"
    """

    targetHeader: str | None = Field(
        None, max_length=256, pattern="^[A-Za-z0-9!#$%&'*+\\-.^_|~]+$"
    )
    """
    TargetHeader selects the request header replaced by the legacy
    single-header mode. It is used only when TargetHeaders is omitted and is
    otherwise ignored. When omitted in legacy mode, implementations preserve
    the legacy behavior of targeting Authorization.
    """
    targetHeaders: TargetHeaders | None = None
    """
    TargetHeaders enables selector mode and selects the request headers to
    replace. When set, Value supplies the value for every selected header and
    When, TargetHeader, and ValueTemplate are ignored.
    """
    value: Value | None = None
    """
    Value produces the replacement value for every header selected by
    TargetHeaders. It is used only when TargetHeaders is set and is otherwise
    ignored. Its Cel branch must return a string and may read request, pod,
    profile, rule, inputs, token, header.name, and header.value. Its Template
    branch may read Request, Pod, Profile, Rule, Inputs, Token, and Header.
    """
    valueTemplate: str | None = Field(None, max_length=1024, min_length=1)
    """
    ValueTemplate renders the replacement value in the legacy single-header
    mode. It is used only when TargetHeaders is omitted and is otherwise
    ignored.
    """
    when: When | None = None
    """
    When gates the legacy single-header mode on a matching request header.
    It is used only when TargetHeaders is omitted and is otherwise ignored.
    """


class AuditItem(BaseModel):
    """
    AuditAction defines an asynchronous audit event. Audit processing does not
    change the request result.

    Audit actions may be configured at two levels:
      - SecurityProfileSpec.Audit: profile-wide defaults applied to every
        matched rule.
      - SecurityRuleActions.Audit: per-rule overrides. When non-empty, the
        spec-level list is suppressed for that rule's matches.

    Each action is evaluated for every matching rule. An empty When expression
    always matches.
    """

    name: str = Field(
        ..., max_length=63, min_length=1, pattern="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
    )
    """
    Name uniquely identifies this action within its containing list.
    """
    webhook: Webhook
    """
    Webhook is the destination for this action.
    """
    when: str | None = Field(None, max_length=1024)
    """
    When is a CEL expression that determines whether the event is emitted.
    It must evaluate to a boolean. An empty expression evaluates to true.

    A compilation error prevents the profile from compiling. A runtime
    evaluation error drops the event.

    Available variables:
      result   string                  one of passthrough/mutated/blocked/bypassed/error
      request  map<string, dyn>        host, port, path, method, scheme, headers, queryParams
      pod      map<string, dyn>        name, namespace, ip, labels
      profile  map<string, string>     name, namespace
      rule     map<string, string>     name (the matched rule's name)
      inputs   map<string, dyn>        profile-scoped inputs
      response map<string, dyn>        status

    Examples:
      result == "blocked"
      result in ["blocked", "bypassed"]
      pod.labels["team"] == "fraud" && result != "passthrough"
      rule.name.startsWith("pii-")
    """


class AuditItem1(BaseModel):
    """
    AuditAction defines an asynchronous audit event. Audit processing does not
    change the request result.

    Audit actions may be configured at two levels:
      - SecurityProfileSpec.Audit: profile-wide defaults applied to every
        matched rule.
      - SecurityRuleActions.Audit: per-rule overrides. When non-empty, the
        spec-level list is suppressed for that rule's matches.

    Each action is evaluated for every matching rule. An empty When expression
    always matches.
    """

    name: str = Field(
        ..., max_length=63, min_length=1, pattern="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
    )
    """
    Name uniquely identifies this action within its containing list.
    """
    webhook: Webhook1
    """
    Webhook is the destination for this action.
    """
    when: str | None = Field(None, max_length=1024)
    """
    When is a CEL expression that determines whether the event is emitted.
    It must evaluate to a boolean. An empty expression evaluates to true.

    A compilation error prevents the profile from compiling. A runtime
    evaluation error drops the event.

    Available variables:
      result   string                  one of passthrough/mutated/blocked/bypassed/error
      request  map<string, dyn>        host, port, path, method, scheme, headers, queryParams
      pod      map<string, dyn>        name, namespace, ip, labels
      profile  map<string, string>     name, namespace
      rule     map<string, string>     name (the matched rule's name)
      inputs   map<string, dyn>        profile-scoped inputs
      response map<string, dyn>        status

    Examples:
      result == "blocked"
      result in ["blocked", "bypassed"]
      pod.labels["team"] == "fraud" && result != "passthrough"
      rule.name.startsWith("pii-")
    """


class Block(BaseModel):
    """
    Block is a terminal action that returns a configured HTTP response
    to the client without forwarding upstream.
    """

    body: str | None = None
    """
    Body is an optional response body sent verbatim to the client.
    """
    statusCode: int | None = Field(403, ge=100, le=599)
    """
    StatusCode is the HTTP status returned to the client.
    """


class Body(BaseModel):
    """
    Body configures the request body. When omitted, the request has an empty
    body.
    """

    json_: dict[str, Any] | None = Field(None, alias="json")
    """
    JSON is a structured body. String values are rendered as Go templates;
    other values are preserved. The content type is application/json.
    """
    text: str | None = Field(None, max_length=8192)
    """
    Text is a Go template rendered as a text/plain body.
    """


class Condition(BaseModel):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """

    lastTransitionTime: AwareDatetime
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
    """
    message: str = Field(..., max_length=32768)
    """
    message is a human readable message indicating details about the transition.
    This may be an empty string.
    """
    observedGeneration: int | None = Field(None, ge=0)
    """
    observedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str = Field(
        ...,
        max_length=1024,
        min_length=1,
        pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
    )
    """
    reason contains a programmatic identifier indicating the reason for the condition's last transition.
    Producers of specific condition types may define expected values and meanings for this field,
    and whether the values are considered a guaranteed API.
    The value should be a CamelCase string.
    This field may not be empty.
    """
    status: Status1
    """
    status of the condition, one of True, False, Unknown.
    """
    type: str = Field(
        ...,
        max_length=316,
        pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
    )
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    """


class ConfigMap(BaseModel):
    """
    ConfigMap sources the input values from a ConfigMap's data.
    """

    name: str = Field(..., max_length=253, min_length=1)
    """
    Name is the ConfigMap name.
    """
    namespace: str | None = Field(None, max_length=63)
    """
    Namespace is the ConfigMap namespace. When omitted, a SecurityProfile
    uses its own namespace. A GlobalSecurityProfile must set this field.
    """


class CredentialProvider(BaseModel):
    """
    CredentialProvider fetches credentials from an external provider.
    """

    name: str = Field(..., max_length=253, min_length=1)
    """
    Name is the provider name.
    """
    namespace: str | None = Field(None, max_length=253, min_length=1)
    """
    Namespace is reserved for namespace-scoped provider lookup. It is
    currently ignored.
    """
    parameters: dict[str, Parameters] | None = None
    """
    Parameters supplies values rendered into the provider request's
    extraMetadata field.
    """


class CredentialRef(BaseModel):
    """
    CredentialRef identifies the credential source.
    """

    credentialProvider: CredentialProvider | None = None
    """
    CredentialProvider fetches credentials from an external provider.
    """
    kind: Kind | None = None
    """
    Kind identifies the deprecated credential source type.
    Deprecated: use Secret or CredentialProvider.
    """
    name: str | None = Field(None, max_length=253, min_length=1)
    """
    Name identifies the deprecated credential source.
    Deprecated: use Secret or CredentialProvider.
    """
    namespace: str | None = Field(None, max_length=253, min_length=1)
    """
    Namespace is used by deprecated Secret references. It is ignored by
    deprecated CredentialProvider references.
    Deprecated: use Secret.Namespace instead.
    """
    secret: Secret | None = None
    """
    Secret references credentials stored in a Kubernetes Secret.
    """


class DefaultAction(StrEnum):
    """
    DefaultAction is the decision applied when no rule matches.
    Defaults to "deny" (whitelist mode); set "allow" for blacklist mode.
    """

    allow = "allow"
    deny = "deny"


class DenyResponse(BaseModel):
    """
    DenyResponse configures the HTTP response when a tool is denied.
    """

    body: str | None = None
    """
    Body is the optional response body sent to the client.
    """
    statusCode: int | None = Field(403, ge=100, le=599)
    """
    StatusCode is the HTTP status returned to the client. Defaults to 403.
    """


class FailStrategy(StrEnum):
    """
    FailStrategy controls behavior when the transformation fails.
    Defaults to Block (fail closed).
    """

    Allow = "Allow"
    Block = "Block"
    Ignore = "Ignore"


class GlobalSecurityProfile(BaseModel):
    """
    GlobalSecurityProfile defines cluster-scoped L7 security policy for
    selected Pods in all namespaces. Global and namespaced profiles share the
    same priority ordering.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec | None = None
    """
    SecurityProfileSpec defines L7 security policy for selected Pods.
    """
    status: Status | None = None
    """
    SecurityProfileStatus captures the observed state of a SecurityProfile.
    """


class Header(BaseModel):
    """
    AuditHeader defines one HTTP header on an audit request.
    """

    name: str = Field(
        ..., max_length=256, min_length=1, pattern="^[A-Za-z0-9!#$%&'*+\\-.^_|~]+$"
    )
    """
    Name is the header name. Restricted to a safe subset of RFC 7230
    tchar characters.
    """
    value: str = Field(..., max_length=2048)
    """
    Value is a Go template that renders the header value.
    """


class Header2(BaseModel):
    """
    HeaderMatch filters a request by a single header's value.
    Multiple HeaderMatch entries in one RuleMatch are ANDed.
    """

    name: str = Field(
        ..., max_length=256, min_length=1, pattern="^[A-Za-z0-9!#$%&'*+\\-.^_|~]+$"
    )
    """
    Name is the header name (case-insensitive). Restricted to a safe
    subset of RFC 7230 tchar characters.
    """
    type: Type1 | None = "Exact"
    """
    Type selects the matching strategy. Defaults to Exact.
    """
    value: str = Field(..., max_length=512, min_length=1)
    """
    Value is the match operand. For Exact/Prefix it is compared
    verbatim; for Regex it is interpreted as an RE2 expression.
    """


class HeaderManipulation(BaseModel):
    """
    HeaderManipulation sets or removes plaintext request headers.
    Non-terminal. Values are stored verbatim — use TokenTransformation
    for credentials.
    """

    remove: list[RemoveItem] | None = Field(None, max_length=16)
    """
    Remove lists header names to strip from the request before it is
    forwarded upstream. Names must be lowercase; header names are
    case-insensitive on the wire. A name may not appear in both Set and
    Remove.
    """
    set: list[SetItem] | None = Field(None, max_length=16)
    """
    Set adds or replaces headers. An existing header with the same
    name is replaced.
    """


class Input(BaseModel):
    """
    SecurityProfileInput defines one named input source. Exactly one of
    ConfigMap or Inline must be set.
    """

    configMap: ConfigMap | None = None
    """
    ConfigMap sources the input values from a ConfigMap's data.
    """
    inline: dict[str, str] | None = None
    """
    Inline declares the input values directly in the profile.
    """
    name: str = Field(
        ..., max_length=63, min_length=1, pattern="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
    )
    """
    Name uniquely identifies this input within the profile.
    """


class Kind(StrEnum):
    """
    Kind identifies the deprecated credential source type.
    Deprecated: use Secret or CredentialProvider.
    """

    Secret = "Secret"
    CredentialProvider = "CredentialProvider"


class MatchExpression(BaseModel):
    """
    A label selector requirement is a selector that contains values, a key, and an operator that
    relates the key and values.
    """

    key: str
    """
    key is the label key that the selector applies to.
    """
    operator: str
    """
    operator represents a key's relationship to a set of values.
    Valid operators are In, NotIn, Exists and DoesNotExist.
    """
    values: list[str] | None = None
    """
    values is an array of string values. If the operator is In or NotIn,
    the values array must be non-empty. If the operator is Exists or DoesNotExist,
    the values array must be empty. This array is replaced during a strategic
    merge patch.
    """


class MatchItem(BaseModel):
    """
    RuleMatch is a conjunctive match condition. Multiple RuleMatch entries
    inside a rule's match list are ORed; fields inside one RuleMatch are ANDed.

    Domains is required. All other fields further restrict the match.
    """

    domains: list[str] = Field(..., min_length=1)
    """
    Domains lists target host names. Supports "*" (any domain) and
    "*.example.com" wildcard prefixes.

    CAUTION: wildcard and specific domains can both match the same request
    under Default Continue semantics, so rule ordering matters.
    """
    headers: list[Header2] | None = None
    """
    Headers lists header matches; multiple entries are ANDed.
    """
    methods: list[Method2] | None = None
    """
    Methods lists HTTP methods. Multiple entries are ORed.
    """
    paths: list[Path] | None = None
    """
    Paths lists URL path matches. Multiple entries are ORed. The query
    string is excluded from path matching.
    """
    ports: list[Port] | None = None
    """
    Ports lists destination ports. Multiple entries are ORed.

    An explicit authority port is used directly. Otherwise, HTTP defaults
    to 80 and HTTPS defaults to 443. Other schemes have no default port.
    """
    queryParams: list[QueryParam] | None = None
    """
    QueryParams lists URL query parameter matches. Multiple entries are
    ANDed. Values are percent-decoded before matching.
    """
    schemes: list[Scheme] | None = None
    """
    Schemes lists request schemes, such as "http" and "https". Multiple
    entries are ORed, and matching is case-insensitive.
    """


class McpToolPolicy(BaseModel):
    """
    MCPToolPolicy defines inline MCP tool access control rules.
    Non-terminal when the policy allows; terminal (like Block) when
    denied.
    """

    defaultAction: DefaultAction
    """
    DefaultAction is the decision applied when no rule matches.
    Defaults to "deny" (whitelist mode); set "allow" for blacklist mode.
    """
    denyResponse: DenyResponse | None = None
    """
    DenyResponse configures the HTTP response when a tool is denied.
    """
    rules: list[Rule1] = Field(..., min_length=1)
    """
    Rules are evaluated in order. First match wins.
    """
    unsupportedVersionAction: UnsupportedVersionAction | None = "deny"
    """
    UnsupportedVersionAction determines how a tools/call request with a
    missing or unsupported MCP-Protocol-Version header is handled. "deny"
    rejects the request, while "passthrough" skips policy evaluation.
    """


class Method(StrEnum):
    """
    Method is the HTTP request method. Defaults to POST.
    """

    POST = "POST"
    PUT = "PUT"
    PATCH = "PATCH"


class Method2(StrEnum):
    GET = "GET"
    HEAD = "HEAD"
    POST = "POST"
    PUT = "PUT"
    PATCH = "PATCH"
    DELETE = "DELETE"
    OPTIONS = "OPTIONS"
    CONNECT = "CONNECT"
    TRACE = "TRACE"


class Name(RootModel[str]):
    root: str = Field(
        ..., max_length=256, min_length=1, pattern="^[A-Za-z0-9!#$%&'*+\\-.^_|~]+$"
    )


class Parameters(BaseModel):
    """
    ValueSource produces one configuration value. Exactly one of Value, Cel, or
    Template must be set. Value and Template produce strings. The containing
    field documents the evaluation context and required result type for Cel.
    """

    cel: str | None = Field(None, max_length=1024, min_length=1)
    """
    Cel is a CEL expression evaluated in the context documented by the
    containing field.
    """
    template: str | None = Field(None, max_length=2048, min_length=1)
    """
    Template is a Go template evaluated in the context documented by the
    containing field. Its rendered output is the value.
    """
    value: str | None = Field(None, max_length=2048)
    """
    Value is a static string emitted verbatim.
    """


class Path(BaseModel):
    """
    PathMatch specifies how to match the request URL path.
    """

    type: Type2
    """
    Type selects the path matching strategy. Defaults to Prefix.
    """
    value: str = Field(..., max_length=256, min_length=1)
    """
    Value is the match value. For Regex, it is an RE2 expression.
    """


class Port(RootModel[int]):
    root: int = Field(..., ge=1, le=65535)


class QueryParam(BaseModel):
    """
    QueryParamMatch filters a request by one URL query parameter.
    Multiple QueryParamMatch entries in one RuleMatch are ANDed.

    When a key appears more than once, only its first value is matched.
    """

    name: str = Field(
        ...,
        max_length=256,
        min_length=1,
        pattern="^[A-Za-z0-9!$&'()*+,\\-./:;=?@_~\\[\\]]+$",
    )
    """
    Name is the case-sensitive query parameter name.
    """
    type: Type3 | None = "Exact"
    """
    Type selects the matching strategy. Defaults to Exact.
    """
    value: str = Field(..., max_length=512, min_length=1)
    """
    Value is the match operand. For Exact/Prefix it is compared
    verbatim against the percent-decoded query value; for Regex it is
    interpreted as an RE2 expression.
    """


class RemoveItem(RootModel[str]):
    root: str = Field(
        ..., max_length=256, min_length=1, pattern="^[a-z0-9!#$%&'*+\\-.^_|~]+$"
    )


class Request(BaseModel):
    """
    Request configures the HTTP request. When omitted, a POST request with an
    empty body is sent.
    """

    body: Body | None = None
    """
    Body configures the request body. When omitted, the request has an empty
    body.
    """
    headers: list[Header] | None = None
    """
    Headers are appended to the request after the default Content-Type
    header.
    """
    method: Method | None = "POST"
    """
    Method is the HTTP request method. Defaults to POST.
    """


class Request1(BaseModel):
    """
    Request configures the HTTP request. When omitted, a POST request with an
    empty body is sent.
    """

    body: Body | None = None
    """
    Body configures the request body. When omitted, the request has an empty
    body.
    """
    headers: list[Header] | None = None
    """
    Headers are appended to the request after the default Content-Type
    header.
    """
    method: Method | None = "POST"
    """
    Method is the HTTP request method. Defaults to POST.
    """


class Rule(BaseModel):
    """
    SecurityRule is one entry in the ordered rule chain.

    Every matching rule executes in order until an action terminates the
    request. Mutations from earlier rules are preserved by Bypass and discarded
    by Block. A wildcard match does not prevent later, more specific rules from
    matching.
    """

    actions: Actions
    """
    Actions configures the actions executed when this rule matches.
    """
    match: list[MatchItem] = Field(..., min_length=1)
    """
    Match lists match conditions. Multiple entries are ORed.
    """
    name: str = Field(..., max_length=253, min_length=1)
    """
    Name uniquely identifies the rule within the profile. Used in
    metrics and events.
    """


class Rule1(BaseModel):
    """
    MCPToolPolicyRule defines one allow or deny rule for an MCP tool call.
    """

    action: Action
    """
    Action determines whether the matching tool call is allowed or denied.
    """
    method: str = Field(..., min_length=1)
    """
    Method is the JSON-RPC method. Only "tools/call" is currently enforced;
    other methods pass through without policy evaluation.
    """
    toolNames: list[str] | None = None
    """
    ToolNames lists values matched against params.name. Multiple entries are
    ORed. An empty list matches any tool name.
    """


class Scheme(RootModel[str]):
    root: str = Field(
        ..., max_length=32, min_length=1, pattern="^[a-zA-Z][a-zA-Z0-9+\\-.]*$"
    )


class Secret(BaseModel):
    """
    Secret references credentials stored in a Kubernetes Secret.
    """

    name: str = Field(..., max_length=253, min_length=1)
    """
    Name is the Secret name.
    """
    namespace: str | None = Field(None, max_length=253, min_length=1)
    """
    Namespace is the Secret namespace. When omitted, a SecurityProfile uses
    its own namespace and a GlobalSecurityProfile uses the selected Pod's
    namespace.
    """


class Selector(BaseModel):
    """
    Selector chooses the Pods to which this profile applies. An empty
    selector matches every Pod in scope.
    """

    matchExpressions: list[MatchExpression] | None = None
    """
    matchExpressions is a list of label selector requirements. The requirements are ANDed.
    """
    matchLabels: dict[str, str] | None = None
    """
    matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
    map is equivalent to an element of matchExpressions, whose key field is "key", the
    operator is "In", and the values array contains only "value". The requirements are ANDed.
    """


class SetItem(BaseModel):
    """
    HeaderValue is one plaintext header assignment.
    """

    name: str = Field(
        ..., max_length=256, min_length=1, pattern="^[a-z0-9!#$%&'*+\\-.^_|~]+$"
    )
    """
    Name is the header name. It must be lowercase so that the list map
    key matches HTTP's case-insensitive header semantics; the data plane
    emits it verbatim. Restricted to a safe lowercase subset of RFC 7230
    tchar characters.
    """
    value: str = Field(..., max_length=2048)
    """
    Value is stored and injected verbatim. NOT for credentials.
    """


class Spec(BaseModel):
    """
    SecurityProfileSpec defines L7 security policy for selected Pods.
    """

    audit: list[AuditItem] | None = None
    """
    Audit defines the audit actions inherited by rules that do not configure
    their own Audit list.
    """
    inputs: list[Input] | None = None
    """
    Inputs defines named values available to CEL expressions and Go
    templates in this profile.
    """
    priority: int | None = Field(1000, ge=0)
    """
    Priority determines evaluation order when multiple profiles match a Pod.
    Lower values run first. Ties are resolved by creation time, name, and
    namespace. Defaults to DefaultSecurityProfilePriority.
    """
    rules: list[Rule] | None = None
    """
    Rules is the ordered rule chain. Every matching rule executes until an
    action terminates the request. Rules from matching profiles are combined
    in profile evaluation order. An empty list forwards all traffic.
    """
    selector: Selector
    """
    Selector chooses the Pods to which this profile applies. An empty
    selector matches every Pod in scope.
    """


class Status(BaseModel):
    """
    SecurityProfileStatus captures the observed state of a SecurityProfile.
    """

    conditions: list[Condition] | None = None
    """
    Conditions summarizes the profile's current state.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the .metadata.generation last reconciled.
    """


class Status1(StrEnum):
    """
    status of the condition, one of True, False, Unknown.
    """

    True_ = "True"
    False_ = "False"
    Unknown = "Unknown"


class TargetHeaders(BaseModel):
    """
    TargetHeaders enables selector mode and selects the request headers to
    replace. When set, Value supplies the value for every selected header and
    When, TargetHeader, and ValueTemplate are ignored.
    """

    cel: str | None = Field(None, max_length=1024, min_length=1)
    """
    Cel selects request header names dynamically and must return a
    list<string>. The expression may read the request, Pod, profile, rule,
    and inputs context, but not the retrieved token.
    """
    names: list[Name] | None = Field(None, max_length=64, min_length=1)
    """
    Names is a static set of request header names. Every selected header uses
    the same value rule.
    """


class TokenTransformation(BaseModel):
    """
    TokenTransformation rewrites request credentials.
    Non-terminal.
    """

    apiKey: ApiKey | None = None
    """
    ApiKey configures an ApiKey transformation. It is required for ApiKey and
    ignored for AliyunSTS. When targetHeaders is set, targetHeaders and value
    take precedence and when, targetHeader, and valueTemplate are ignored.
    Otherwise, the legacy when, targetHeader, and valueTemplate fields apply
    and value is ignored.

    Examples:

    The following example writes the same rendered token value to two fixed
    request headers:

        apiKey:
          targetHeaders:
            names:
            - authorization
            - x-backend-authorization
          value:
            template: "Bearer {{ .Token }}"

    The following example selects every existing request header whose value
    is the token placeholder and replaces each matched value with the token:

        apiKey:
          targetHeaders:
            cel: |
              request.headers.filter(
                name,
                request.headers[name] == "${AGENTIO_TOKEN}"
              )
          value:
            template: "{{ .Token }}"
    """
    credentialRef: CredentialRef
    """
    CredentialRef identifies the credential source.
    """
    disabled: bool | None = False
    """
    Disabled skips the action without removing its configuration.
    """
    failStrategy: FailStrategy | None = "Block"
    """
    FailStrategy controls behavior when the transformation fails.
    Defaults to Block (fail closed).
    """
    type: Type | None = "ApiKey"
    """
    Type discriminates the transformation strategy. Defaults to ApiKey.
    """


class Type(StrEnum):
    """
    Type discriminates the transformation strategy. Defaults to ApiKey.
    """

    ApiKey = "ApiKey"
    AliyunSTS = "AliyunSTS"


class Type1(StrEnum):
    """
    Type selects the matching strategy. Defaults to Exact.
    """

    Exact = "Exact"
    Prefix = "Prefix"
    Regex = "Regex"


class Type2(StrEnum):
    """
    Type selects the path matching strategy. Defaults to Prefix.
    """

    Prefix = "Prefix"
    Exact = "Exact"
    Regex = "Regex"


class Type3(StrEnum):
    """
    Type selects the matching strategy. Defaults to Exact.
    """

    Exact = "Exact"
    Prefix = "Prefix"
    Regex = "Regex"


class UnsupportedVersionAction(StrEnum):
    """
    UnsupportedVersionAction determines how a tools/call request with a
    missing or unsupported MCP-Protocol-Version header is handled. "deny"
    rejects the request, while "passthrough" skips policy evaluation.
    """

    deny = "deny"
    passthrough = "passthrough"


class Value(BaseModel):
    """
    Value produces the replacement value for every header selected by
    TargetHeaders. It is used only when TargetHeaders is set and is otherwise
    ignored. Its Cel branch must return a string and may read request, pod,
    profile, rule, inputs, token, header.name, and header.value. Its Template
    branch may read Request, Pod, Profile, Rule, Inputs, Token, and Header.
    """

    cel: str | None = Field(None, max_length=1024, min_length=1)
    """
    Cel is a CEL expression evaluated in the context documented by the
    containing field.
    """
    template: str | None = Field(None, max_length=2048, min_length=1)
    """
    Template is a Go template evaluated in the context documented by the
    containing field. Its rendered output is the value.
    """
    value: str | None = Field(None, max_length=2048)
    """
    Value is a static string emitted verbatim.
    """


class Webhook(BaseModel):
    """
    Webhook is the destination for this action.
    """

    request: Request | None = None
    """
    Request configures the HTTP request. When omitted, a POST request with an
    empty body is sent.
    """
    timeout: str | None = "2s"
    """
    Timeout limits each HTTP attempt. Defaults to 2s and must be between
    500ms and 30s.
    """
    url: str = Field(..., max_length=2048, min_length=1)
    """
    URL is an absolute HTTP or HTTPS URL rendered as a Go template. The
    event is dropped if rendering fails or the rendered URL is invalid.
    """


class Webhook1(BaseModel):
    """
    Webhook is the destination for this action.
    """

    request: Request1 | None = None
    """
    Request configures the HTTP request. When omitted, a POST request with an
    empty body is sent.
    """
    timeout: str | None = "2s"
    """
    Timeout limits each HTTP attempt. Defaults to 2s and must be between
    500ms and 30s.
    """
    url: str = Field(..., max_length=2048, min_length=1)
    """
    URL is an absolute HTTP or HTTPS URL rendered as a Go template. The
    event is dropped if rendering fails or the rendered URL is invalid.
    """


class When(BaseModel):
    """
    When gates the legacy single-header mode on a matching request header.
    It is used only when TargetHeaders is omitted and is otherwise ignored.
    """

    header: str = Field(
        ..., max_length=256, min_length=1, pattern="^[A-Za-z0-9!#$%&'*+\\-.^_|~]+$"
    )
    """
    Header is the request header name to inspect.
    """
    pattern: str = Field(..., max_length=512, min_length=1)
    """
    Pattern is an RE2 regex evaluated against the header value.
    """
