# generated by datamodel-codegen:
#   filename:  poolautoscaler_schema.json
#   timestamp: 2026-09-03T05:22:23+00:00

from __future__ import annotations

from enum import StrEnum

from kubernetes.client.models import V1ObjectMeta
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AppliedCronPolicy(BaseModel):
    """
    CronScalingPolicyStatus records the last schedule time for a cron policy.
    """

    lastScheduleTime: AwareDatetime | None = None
    """
    LastScheduleTime is the last time the policy was successfully scheduled.
    """
    name: str
    """
    Name is the cron policy name.
    """


class CapacityPolicy(BaseModel):
    """
    CapacityPolicy defines the capacity configuration of the target resource pool.
    """

    scaleDown: ScaleDown | None = None
    """
    ScaleDown is the scaling rule for scaling down.
    """
    scaleUp: ScaleUp | None = None
    """
    ScaleUp is the scaling rule for scaling up.
    """
    targetAvailable: int | str
    """
    TargetAvailable is the desired available replicas.
    Can be an absolute number (ex: 5) or a percentage of current replicas (ex: 70%).
    When the pool is empty, a percentage target is bootstrapped against
    maxReplicas so the pool can seed its initial idle capacity.
    """
    tolerance: int | str | None = None
    """
    Tolerance is the tolerance between the watermark and desired value under which
    no updates are made to the desired number of replicas.
    Can be an absolute number (ex: 5) or a percentage (ex: 10%).
    If not set, defaults to 10%.
    A percentage tolerance is always resolved against the target value:
    when targetAvailable is also a percentage, both percentages are combined
    first and applied to the pool size; when targetAvailable is an absolute
    number, the percentage tolerance is applied to that resolved target
    (e.g. targetAvailable=5 with tolerance=10% yields watermarks [4, 6]).
    """


class Condition(BaseModel):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """

    lastTransitionTime: AwareDatetime
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
    """
    message: str = Field(..., max_length=32768)
    """
    message is a human readable message indicating details about the transition.
    This may be an empty string.
    """
    observedGeneration: int | None = Field(None, ge=0)
    """
    observedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str = Field(
        ...,
        max_length=1024,
        min_length=1,
        pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
    )
    """
    reason contains a programmatic identifier indicating the reason for the condition's last transition.
    Producers of specific condition types may define expected values and meanings for this field,
    and whether the values are considered a guaranteed API.
    The value should be a CamelCase string.
    This field may not be empty.
    """
    status: Status1
    """
    status of the condition, one of True, False, Unknown.
    """
    type: str = Field(
        ...,
        max_length=316,
        pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
    )
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    """


class CronPolicy(BaseModel):
    """
    CronScalingPolicy defines the cron-based scaling configuration for the resource pool.
    """

    name: str
    """
    Name is used to specify the scaling policy.
    """
    schedule: str
    """
    Schedule is a cron expression that defines when this policy should be executed.
    Supports standard cron format with 5 fields (minute hour day month weekday).
    """
    targetReplicas: int = Field(..., ge=0)
    """
    TargetReplicas is the desired replicas when this policy executes.
    """
    timeZone: str | None = None
    """
    TimeZone is the time zone name for the given schedule, e.g. "Asia/Shanghai", "UTC".
    If not specified, this will default to the time zone of the autoscaler controller manager process.
    """


class CurrentCapacity(BaseModel):
    """
    CurrentCapacity is the last read state of the capacity used by this autoscaler.
    """

    available: int
    """
    Available is current number of available pods managed by this autoscaler.
    """


class Kind(StrEnum):
    """
    Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """

    SandboxSet = "SandboxSet"


class PoolAutoscaler(BaseModel):
    """
    PoolAutoscaler is the configuration for a warming pool autoscaler,
    which automatically manages the replica count of the warming pool
    based on the policies specified.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec
    """
    Spec defines the desired behavior of the autoscaler.
    """
    status: Status | None = None
    """
    Status is the current information about the autoscaler.
    """


class ScaleDown(BaseModel):
    """
    ScaleDown is the scaling rule for scaling down.
    """

    stabilizationWindowSeconds: int | None = Field(None, ge=60, le=3600)
    """
    StabilizationWindowSeconds is the cooldown period after any scale action before
    a scale in this direction is allowed. This is a cooldown model: the first scale
    action is immediate, subsequent actions must wait for the window to elapse since
    the most recent scale action (in either direction).
    Must be >= 60 and <= 3600 (one hour) when set.
    Scale-up defaults to 60 seconds when omitted and is normalized at runtime to at
    least the process-wide Sandbox Pending timeout plus 10 seconds.
    Scale-down defaults to 300 seconds when omitted.
    """


class ScaleTargetRef(BaseModel):
    """
    ScaleTargetRef points to the target warming pool to scale, and is used to select the pods for which instance status
    should be collected, as well as to actually change the replica count.
    """

    apiVersion: str | None = None
    """
    API version of the referent
    """
    kind: Kind
    """
    Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    name: str
    """
    Name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """


class ScaleUp(BaseModel):
    """
    ScaleUp is the scaling rule for scaling up.
    """

    stabilizationWindowSeconds: int | None = Field(None, ge=60, le=3600)
    """
    StabilizationWindowSeconds is the cooldown period after any scale action before
    a scale in this direction is allowed. This is a cooldown model: the first scale
    action is immediate, subsequent actions must wait for the window to elapse since
    the most recent scale action (in either direction).
    Must be >= 60 and <= 3600 (one hour) when set.
    Scale-up defaults to 60 seconds when omitted and is normalized at runtime to at
    least the process-wide Sandbox Pending timeout plus 10 seconds.
    Scale-down defaults to 300 seconds when omitted.
    """


class Spec(BaseModel):
    """
    Spec defines the desired behavior of the autoscaler.
    """

    capacityPolicy: CapacityPolicy | None = None
    """
    CapacityPolicy defines the capacity configuration of the target resource pool.
    """
    cronPolicies: list[CronPolicy] | None = Field(None, max_length=20)
    """
    CronPolicies is a list of potential cron scaling policies which can be used during scaling.
    When both CronPolicies and CapacityPolicy are set, CronPolicies takes higher priority.
    """
    maxReplicas: int = Field(..., ge=1)
    """
    MaxReplicas is the upper limit for the number of replicas to which the autoscaler can scale up.
    It cannot be less than minReplicas.
    """
    minReplicas: int | None = Field(0, ge=0)
    """
    MinReplicas is the lower limit for the number of replicas to which the autoscaler
    can scale down. It defaults to 0 pods.
    """
    scaleTargetRef: ScaleTargetRef
    """
    ScaleTargetRef points to the target warming pool to scale, and is used to select the pods for which instance status
    should be collected, as well as to actually change the replica count.
    """
    suspend: bool | None = None
    """
    Suspend tells the controller to suspend subsequent executions.
    Defaults to false.
    """


class Status(BaseModel):
    """
    Status is the current information about the autoscaler.
    """

    appliedCronPolicies: list[AppliedCronPolicy] | None = None
    """
    AppliedCronPolicies is the execution status of cron policies.
    """
    conditions: list[Condition] | None = None
    """
    Conditions is the set of conditions required for this autoscaler to scale its target.
    """
    currentCapacity: CurrentCapacity | None = None
    """
    CurrentCapacity is the last read state of the capacity used by this autoscaler.
    """
    currentReplicas: int
    """
    CurrentReplicas is current number of replicas of pods managed by this autoscaler.
    """
    desiredReplicas: int
    """
    DesiredReplicas is the desired number of replicas of pods managed by this autoscaler.
    """
    lastScaleTime: AwareDatetime | None = None
    """
    LastScaleTime is the last time the PoolAutoscaler scaled the number of pods.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the most recent generation observed by this autoscaler.
    """
    suspended: bool | None = None
    """
    Suspended indicates whether the autoscaler is currently suspended.
    """


class Status1(StrEnum):
    """
    status of the condition, one of True, False, Unknown.
    """

    True_ = "True"
    False_ = "False"
    Unknown = "Unknown"
