# generated by datamodel-codegen:
#   filename:  sandboxupdateops_schema.json
#   timestamp: 2026-09-03T05:22:25+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from kubernetes.client.models import V1ObjectMeta
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Condition(BaseModel):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """

    lastTransitionTime: AwareDatetime
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
    """
    message: str = Field(..., max_length=32768)
    """
    message is a human readable message indicating details about the transition.
    This may be an empty string.
    """
    observedGeneration: int | None = Field(None, ge=0)
    """
    observedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str = Field(
        ...,
        max_length=1024,
        min_length=1,
        pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
    )
    """
    reason contains a programmatic identifier indicating the reason for the condition's last transition.
    Producers of specific condition types may define expected values and meanings for this field,
    and whether the values are considered a guaranteed API.
    The value should be a CamelCase string.
    This field may not be empty.
    """
    status: Status1
    """
    status of the condition, one of True, False, Unknown.
    """
    type: str = Field(
        ...,
        max_length=316,
        pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
    )
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    """


class Exec(BaseModel):
    """
    Exec specifies the command to execute inside the sandbox via envd.
    The first element is the command, the rest are args.
    For shell scripts, use: ["/bin/bash", "-c", "your-script"]
    """

    command: list[str] | None = None
    """
    Command is the command line to execute inside the container, the working directory for the
    command  is root ('/') in the container's filesystem. The command is simply exec'd, it is
    not run inside a shell, so traditional shell instructions ('|', etc) won't work. To use
    a shell, you need to explicitly call out to that shell.
    Exit status of 0 is treated as live/healthy and non-zero is unhealthy.
    """


class Lifecycle(BaseModel):
    """
    Lifecycle defines pre/post upgrade hooks to set on each sandbox during upgrade.
    """

    postUpgrade: PostUpgrade | None = None
    """
    PostUpgrade is the action executed after the upgrade.
    It is typically used to restore workspace data.
    """
    preUpgrade: PreUpgrade | None = None
    """
    PreUpgrade is the action executed before the upgrade.
    It is typically used to backup workspace data.
    """


class MatchExpression(BaseModel):
    """
    A label selector requirement is a selector that contains values, a key, and an operator that
    relates the key and values.
    """

    key: str
    """
    key is the label key that the selector applies to.
    """
    operator: str
    """
    operator represents a key's relationship to a set of values.
    Valid operators are In, NotIn, Exists and DoesNotExist.
    """
    values: list[str] | None = None
    """
    values is an array of string values. If the operator is In or NotIn,
    the values array must be non-empty. If the operator is Exists or DoesNotExist,
    the values array must be empty. This array is replaced during a strategic
    merge patch.
    """


class PostUpgrade(BaseModel):
    """
    PostUpgrade is the action executed after the upgrade.
    It is typically used to restore workspace data.
    """

    exec: Exec | None = None
    """
    Exec specifies the command to execute inside the sandbox via envd.
    The first element is the command, the rest are args.
    For shell scripts, use: ["/bin/bash", "-c", "your-script"]
    """
    timeoutSeconds: int | None = 60
    """
    TimeoutSeconds is the timeout for the action execution in seconds.
    """


class PreUpgrade(BaseModel):
    """
    PreUpgrade is the action executed before the upgrade.
    It is typically used to backup workspace data.
    """

    exec: Exec | None = None
    """
    Exec specifies the command to execute inside the sandbox via envd.
    The first element is the command, the rest are args.
    For shell scripts, use: ["/bin/bash", "-c", "your-script"]
    """
    timeoutSeconds: int | None = 60
    """
    TimeoutSeconds is the timeout for the action execution in seconds.
    """


class SandboxUpdateOps(BaseModel):
    """
    SandboxUpdateOps is the Schema for batch sandbox update operations.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec
    """
    Spec defines the desired update operation.
    """
    status: Status | None = None
    """
    Status defines the observed state.
    """


class Selector(BaseModel):
    """
    Selector selects the target sandboxes to update by label.
    """

    matchExpressions: list[MatchExpression] | None = None
    """
    matchExpressions is a list of label selector requirements. The requirements are ANDed.
    """
    matchLabels: dict[str, str] | None = None
    """
    matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
    map is equivalent to an element of matchExpressions, whose key field is "key", the
    operator is "In", and the values array contains only "value". The requirements are ANDed.
    """


class Spec(BaseModel):
    """
    Spec defines the desired update operation.
    """

    lifecycle: Lifecycle | None = None
    """
    Lifecycle defines pre/post upgrade hooks to set on each sandbox during upgrade.
    """
    patch: Any | None = None
    """
    Patch defines the changes to apply to each selected sandbox's template.
    The patch is applied as a Strategic Merge Patch on the sandbox's PodTemplateSpec.
    """
    paused: bool | None = None
    """
    Paused indicates whether the update operation is paused.
    """
    selector: Selector
    """
    Selector selects the target sandboxes to update by label.
    """
    stateFilter: StateFilter | None = None
    """
    StateFilter specifies which sandbox states are eligible as upgrade
    candidates. When empty, defaults to [Running].
    Upgrading sandboxes are always tracked regardless of this field, as they
    represent in-progress upgrades owned by this ops.
    """
    updateStrategy: UpdateStrategy | None = None
    """
    UpdateStrategy defines the strategy for the batch update.
    """


class State(StrEnum):
    """
    SandboxPhase is a label for the condition of a pod at the current time.
    """

    Running = "Running"
    Paused = "Paused"


class StateFilter(BaseModel):
    """
    StateFilter specifies which sandbox states are eligible as upgrade
    candidates. When empty, defaults to [Running].
    Upgrading sandboxes are always tracked regardless of this field, as they
    represent in-progress upgrades owned by this ops.
    """

    states: list[State] | None = None
    """
    States specifies which sandbox phases are eligible as upgrade candidates.
    When empty, defaults to [Running].
    Supported values: Running, Paused.
    """


class Status(BaseModel):
    """
    Status defines the observed state.
    """

    conditions: list[Condition] | None = None
    """
    Conditions represents the latest available observations.
    """
    failedReplicas: int
    """
    FailedReplicas is the number of sandboxes that failed to update.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the most recent generation observed.
    """
    phase: str | None = None
    """
    Phase is the current phase of the update operation.
    """
    replicas: int
    """
    Replicas is the total number of sandboxes selected for update.
    """
    updatedReplicas: int
    """
    UpdatedReplicas is the number of sandboxes that have been successfully updated.
    """
    updatingReplicas: int
    """
    UpdatingReplicas is the number of sandboxes currently being updated.
    """


class Status1(StrEnum):
    """
    status of the condition, one of True, False, Unknown.
    """

    True_ = "True"
    False_ = "False"
    Unknown = "Unknown"


class Type(StrEnum):
    """
    Type specifies the update strategy type.
    When empty, defaults to Recreate.
    Supported values: Recreate, CheckpointRestore.
    """

    Recreate = "Recreate"
    CheckpointRestore = "CheckpointRestore"


class UpdateStrategy(BaseModel):
    """
    UpdateStrategy defines the strategy for the batch update.
    """

    maxUnavailable: int | str | None = None
    """
    MaxUnavailable is the maximum number of sandboxes that can be upgrading at the same time.
    Value can be an absolute number (e.g., 5) or a percentage of total sandboxes (e.g., 10%).
    """
    type: Type | None = None
    """
    Type specifies the update strategy type.
    When empty, defaults to Recreate.
    Supported values: Recreate, CheckpointRestore.
    """
