# generated by datamodel-codegen:
#   filename:  sandboxclaim_schema.json
#   timestamp: 2026-09-03T05:22:24+00:00

from __future__ import annotations

from enum import StrEnum

from kubernetes.client.models import V1ObjectMeta
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Condition(BaseModel):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """

    lastTransitionTime: AwareDatetime
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
    """
    message: str = Field(..., max_length=32768)
    """
    message is a human readable message indicating details about the transition.
    This may be an empty string.
    """
    observedGeneration: int | None = Field(None, ge=0)
    """
    observedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str = Field(
        ...,
        max_length=1024,
        min_length=1,
        pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
    )
    """
    reason contains a programmatic identifier indicating the reason for the condition's last transition.
    Producers of specific condition types may define expected values and meanings for this field,
    and whether the values are considered a guaranteed API.
    The value should be a CamelCase string.
    This field may not be empty.
    """
    status: Status1
    """
    status of the condition, one of True, False, Unknown.
    """
    type: str = Field(
        ...,
        max_length=316,
        pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
    )
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    """


class DynamicVolumesMountItem(BaseModel):
    attributes: dict[str, str] | None = None
    mountID: str | None = None
    mountPath: str
    pvName: str
    readOnly: bool | None = None
    subPath: str | None = None


class InplaceUpdate(BaseModel):
    """
    InplaceUpdate allows to perform inplace update for sandbox while claiming
    """

    image: str | None = None
    """
    Image specifies the new image to update to.
    """
    resources: Resources | None = None
    """
    Resources specifies in-place resource update options.
    """


class Limits1(RootModel[int]):
    root: int = Field(
        ...,
        pattern="^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
    )


class Limits2(RootModel[str]):
    root: str = Field(
        ...,
        pattern="^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
    )


class Limits(RootModel[Limits1 | Limits2]):
    root: Limits1 | Limits2 = Field(
        ...,
        pattern="^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
    )


class Requests1(RootModel[int]):
    root: int = Field(
        ...,
        pattern="^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
    )


class Requests2(RootModel[str]):
    root: str = Field(
        ...,
        pattern="^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
    )


class Requests(RootModel[Requests1 | Requests2]):
    root: Requests1 | Requests2 = Field(
        ...,
        pattern="^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
    )


class Resources(BaseModel):
    """
    Resources specifies in-place resource update options.
    """

    limits: dict[str, Limits] | None = None
    """
    Limits specifies the target resource limits for each container.
    Only CPU and memory are supported; other resource names are rejected.
    The container's original limit must already be set; otherwise the value is ignored.
    A limit must not be lower than the target request of the same resource.
    Memory may only be increased: a target lower than the container's current memory is rejected.
    Memory resize may restart the container when the pod template declares
    resizePolicy: {resourceName: memory, restartPolicy: RestartContainer}.
    The new value must not change the Pod's QoS class; otherwise the claim will be rejected.
    """
    requests: dict[str, Requests] | None = None
    """
    Requests specifies the target resource requests for each container.
    Only CPU and memory are supported; other resource names are rejected.
    The container's original request must already be set; otherwise the value is ignored.
    A request must not exceed the target limit of the same resource.
    Memory may only be increased: a target lower than the container's current memory is rejected.
    Memory resize may restart the container when the pod template declares
    resizePolicy: {resourceName: memory, restartPolicy: RestartContainer}.
    The new value must not change the Pod's QoS class; otherwise the claim will be rejected.
    """


class Runtime(BaseModel):
    name: str


class SandboxClaim(BaseModel):
    """
    SandboxClaim is the Schema for the sandboxclaims API
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec
    """
    spec defines the desired state of SandboxClaim
    """
    status: Status | None = None
    """
    status defines the observed state of SandboxClaim
    """


class Spec(BaseModel):
    """
    spec defines the desired state of SandboxClaim
    """

    annotations: dict[str, str] | None = None
    """
    Annotations contains key-value pairs to be added as annotations
    to claimed Sandbox resources
    """
    claimTimeout: str | None = "1m"
    """
    ClaimTimeout specifies the maximum duration to wait for claiming sandboxes
    If the timeout is reached, the claim will be marked as Completed regardless of
    whether all replicas were successfully claimed
    """
    createOnNoStock: bool | None = True
    """
    CreateOnNoStock allows to create new sandbox if no stock available
    """
    dynamicVolumesMount: list[DynamicVolumesMountItem] | None = None
    """
    DynamicVolumesMount specifies the dynamic volumes to be mounted into the sandbox
    """
    envVars: dict[str, str] | None = None
    """
    EnvVars contains environment variables to be injected into the sandbox
    These will be passed to the sandbox's init endpoint (envd) after claiming
    Only applicable if the SandboxSet has envd enabled
    """
    inplaceUpdate: InplaceUpdate | None = None
    """
    InplaceUpdate allows to perform inplace update for sandbox while claiming
    """
    labels: dict[str, str] | None = None
    """
    Labels contains key-value pairs to be added as labels
    to claimed Sandbox resources and synced to sandbox template labels.
    """
    replicas: int | None = Field(1, ge=1)
    """
    Replicas specifies how many sandboxes to claim (default: 1)
    For batch claiming support
    This field is immutable once set
    """
    reserveFailedSandbox: bool | None = None
    """
    Set ReserveFailedSandbox to true to reserve failed sandboxes
    """
    runtimes: list[Runtime] | None = None
    """
    Runtimes - Runtime configuration for sandbox object
    """
    shutdownTime: AwareDatetime | None = None
    """
    ShutdownTime specifies the absolute time when the sandbox should be shut down
    This will be set as spec.shutdownTime (absolute time) on the Sandbox
    """
    skipInitRuntime: bool | None = False
    """
    SkipInitRuntime allows to skip init runtime for sandbox while claiming
    """
    templateName: str
    """
    TemplateName specifies which SandboxSet pool to claim from
    """
    ttlAfterCompleted: str | None = "60m"
    """
    TTLAfterCompleted specifies the time to live after the claim reaches Completed phase
    After this duration, the SandboxClaim will be automatically deleted.
    Note: Only the SandboxClaim resource will be deleted; the claimed sandboxes will NOT be deleted
    Set to a negative value (e.g., "-1s") to disable automatic deletion (never delete).
    """
    waitReadyTimeout: str | None = "30s"
    """
    WaitReadyTimeout specifies the maximum duration for waiting claimed sandbox ready. Default: 30s.
    A waiting happens when an inplace update happens, a new sandbox created, etc.
    Format: duration string (e.g., "3h", "200s", "15m")
    """


class Status(BaseModel):
    """
    status defines the observed state of SandboxClaim
    """

    claimStartTime: AwareDatetime | None = None
    """
    ClaimStartTime is the timestamp when claiming started
    Used for calculating timeout
    """
    claimedReplicas: int | None = None
    """
    ClaimedReplicas indicates how many sandboxes are currently claimed (total)
    This is determined by querying sandboxes with matching ownerReference
    Only updated during Pending and Claiming phases
    """
    completionTime: AwareDatetime | None = None
    """
    CompletionTime is the timestamp when the claim reached Completed phase
    Used for TTL calculation
    """
    conditions: list[Condition] | None = None
    """
    Conditions represent the current state of the SandboxClaim
    """
    message: str | None = None
    """
    Message provides human-readable details about the current phase
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the most recent generation observed
    """
    phase: str | None = None
    """
    Phase represents the current phase of the claim
    Claiming: In the process of claiming sandboxes
    Completed: Claim process finished (either all replicas claimed or timeout reached)
    """


class Status1(StrEnum):
    """
    status of the condition, one of True, False, Unknown.
    """

    True_ = "True"
    False_ = "False"
    Unknown = "Unknown"
