# generated by datamodel-codegen:
#   filename:  sandboxtemplate_schema.json
#   timestamp: 2026-09-03T05:22:25+00:00

from __future__ import annotations

from enum import StrEnum

from kubernetes.client.models import (
    V1ObjectMeta,
    V1PersistentVolumeClaim,
    V1PodTemplateSpec,
)
from pydantic import BaseModel, ConfigDict, Field


class AutoPausePolicy(BaseModel):
    """
    AutoPausePolicy defines the pause/resume decision rules for sandboxes
    created from this template. It is only informational when a SandboxSet uses
    spec.templateRef: SandboxSetSpec.AutoPausePolicy always takes precedence and
    is what actually reaches created Sandboxes.
    """

    pause: Pause | None = None
    """
    Pause defines the pause policy for the sandbox.
    """
    resume: Resume | None = None
    """
    Resume defines the resume policy for the sandbox.
    """


class Exec(BaseModel):
    """
    Exec specifies a command to execute in the container.
    """

    command: list[str] | None = None
    """
    Command is the command line to execute inside the container, the working directory for the
    command  is root ('/') in the container's filesystem. The command is simply exec'd, it is
    not run inside a shell, so traditional shell instructions ('|', etc) won't work. To use
    a shell, you need to explicitly call out to that shell.
    Exit status of 0 is treated as live/healthy and non-zero is unhealthy.
    """


class Grpc(BaseModel):
    """
    GRPC specifies a GRPC HealthCheckRequest.
    """

    port: int
    """
    Port number of the gRPC service. Number must be in the range 1 to 65535.
    """
    service: str | None = ""
    """
    Service is the name of the service to place in the gRPC HealthCheckRequest
    (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).

    If this is not specified, the default behavior is defined by gRPC.
    """


class HibernateStrategy(BaseModel):
    """
    HibernateStrategy configures the storage medium for hibernate state.
    Only effective when Type is Hibernate.
    """

    type: str | None = None
    """
    Type selects the storage medium for hibernate state.
    """


class HttpGet(BaseModel):
    """
    HTTPGet specifies an HTTP GET request to perform.
    """

    host: str | None = None
    """
    Host name to connect to, defaults to the pod IP. You probably want to set
    "Host" in httpHeaders instead.
    """
    httpHeaders: list[HttpHeader] | None = None
    """
    Custom headers to set in the request. HTTP allows repeated headers.
    """
    path: str | None = None
    """
    Path to access on the HTTP server.
    """
    port: int | str
    """
    Name or number of the port to access on the container.
    Number must be in the range 1 to 65535.
    Name must be an IANA_SVC_NAME.
    """
    scheme: str | None = None
    """
    Scheme to use for connecting to the host.
    Defaults to HTTP.
    """


class HttpHeader(BaseModel):
    """
    HTTPHeader describes a custom header to be used in HTTP probes
    """

    name: str
    """
    The header field name.
    This will be canonicalized upon output, so case-variant names will be understood as the same header.
    """
    value: str
    """
    The header field value
    """


class OnIngressTraffic(BaseModel):
    """
    OnIngressTraffic resumes the sandbox when the sandbox-gateway receives
    inbound traffic addressed to it while it is paused. Unlike the probed
    rules this one is event-driven: it needs no probe, it produces no
    Status.Schedules entry, and it is executed by the sandbox-gateway rather
    than by the sandbox controller.
    """

    pauseTimeout: str | None = None
    """
    PauseTimeout is the auto-pause timeout re-armed by a traffic wake: the
    gateway writes Spec.PauseTime = now + PauseTimeout atomically with
    Spec.Paused = false, so the woken sandbox has running time before its
    next auto-pause. It applies only to auto-pause sandboxes (those that
    already carry Spec.PauseTime); never-timeout and shutdown-only
    sandboxes keep their timeout mode unchanged.
    When absent or non-positive, a traffic wake does not re-arm auto-pause:
    the woken sandbox keeps running until it is paused or deleted again.
    A positive value is subject to the resume timeout floor
    (timeout.DefaultMinResumeTimeoutSeconds, currently 300s): values below
    the floor are raised to it so the fresh PauseTime cannot expire while
    the sandbox is still resuming.
    """


class Pause(BaseModel):
    """
    Pause defines the pause policy for the sandbox.
    """

    whenProbedIdleState: WhenProbedIdleState | None = None
    """
    WhenProbedIdleState pauses the sandbox when a probe's Condition message
    matches MessageRegex for at least ThresholdDuration.
    """


class PauseStrategy(BaseModel):
    """
    PauseStrategy configures how sandboxes created from this template are
    paused when their spec.paused is true. It is only informational when a
    SandboxSet uses spec.templateRef: SandboxSetSpec.PauseStrategy always
    takes precedence and is what actually reaches created Sandboxes.
    """

    hibernateStrategy: HibernateStrategy | None = None
    """
    HibernateStrategy configures the storage medium for hibernate state.
    Only effective when Type is Hibernate.
    """
    type: Type | None = None
    """
    Type selects the pause mechanism.
    """


class Probe(BaseModel):
    """
    Probe defines a named probe that writes its result to a Pod Condition.
    Embeds corev1.Probe inline so that exec/periodSeconds/timeoutSeconds/etc.
    are directly accessible. Currently only exec probes are supported;
    other corev1.Probe fields (httpGet, tcpSocket, grpc) may be supported
    in the future as needed.
    """

    containerName: str | None = None
    """
    ContainerName specifies which container to execute the probe in.
    If empty, defaults to the first container in the pod spec.
    """
    exec: Exec | None = None
    """
    Exec specifies a command to execute in the container.
    """
    failureThreshold: int | None = None
    """
    Minimum consecutive failures for the probe to be considered failed after having succeeded.
    Defaults to 3. Minimum value is 1.
    """
    grpc: Grpc | None = None
    """
    GRPC specifies a GRPC HealthCheckRequest.
    """
    httpGet: HttpGet | None = None
    """
    HTTPGet specifies an HTTP GET request to perform.
    """
    initialDelaySeconds: int | None = None
    """
    Number of seconds after the container has started before liveness probes are initiated.
    More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
    """
    name: str = Field(
        ..., max_length=299, pattern="^[A-Za-z0-9]([-A-Za-z0-9_.]*[A-Za-z0-9])?$"
    )
    """
    Name is the unique identifier for this probe within the sandbox.
    Probe results are written to a Condition with type "agents.kruise.io/<Name>".
    """
    periodSeconds: int | None = None
    """
    How often (in seconds) to perform the probe.
    Default to 10 seconds. Minimum value is 1.
    """
    successThreshold: int | None = None
    """
    Minimum consecutive successes for the probe to be considered successful after having failed.
    Defaults to 1. Must be 1 for liveness and startup. Minimum value is 1.
    """
    tcpSocket: TcpSocket | None = None
    """
    TCPSocket specifies a connection to a TCP port.
    """
    terminationGracePeriodSeconds: int | None = None
    """
    Optional duration in seconds the pod needs to terminate gracefully upon probe failure.
    The grace period is the duration in seconds after the processes running in the pod are sent
    a termination signal and the time when the processes are forcibly halted with a kill signal.
    Set this value longer than the expected cleanup time for your process.
    If this value is nil, the pod's terminationGracePeriodSeconds will be used. Otherwise, this
    value overrides the value provided by the pod spec.
    Value must be non-negative integer. The value zero indicates stop immediately via
    the kill signal (no opportunity to shut down).
    This is a beta field and requires enabling ProbeTerminationGracePeriod feature gate.
    Minimum value is 1. spec.terminationGracePeriodSeconds is used if unset.
    """
    timeoutSeconds: int | None = None
    """
    Number of seconds after which the probe times out.
    Defaults to 1 second. Minimum value is 1.
    More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
    """


class Resume(BaseModel):
    """
    Resume defines the resume policy for the sandbox.
    """

    onIngressTraffic: OnIngressTraffic | None = None
    """
    OnIngressTraffic resumes the sandbox when the sandbox-gateway receives
    inbound traffic addressed to it while it is paused. Unlike the probed
    rules this one is event-driven: it needs no probe, it produces no
    Status.Schedules entry, and it is executed by the sandbox-gateway rather
    than by the sandbox controller.
    """
    whenProbedScheduleTime: WhenProbedScheduleTime | None = None
    """
    WhenProbedScheduleTime resumes the sandbox before a scheduled task
    by parsing the probe's Condition message as a timestamp.
    """


class Runtime(BaseModel):
    name: str


class SandboxTemplate(BaseModel):
    """
    SandboxSet is the Schema for the sandboxsets API, which is an advanced workload for managing sandboxes.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec
    """
    spec defines the desired state of SandboxSet
    """


class Spec(BaseModel):
    """
    spec defines the desired state of SandboxSet
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    autoPausePolicy: AutoPausePolicy | None = None
    """
    AutoPausePolicy defines the pause/resume decision rules for sandboxes
    created from this template. It is only informational when a SandboxSet uses
    spec.templateRef: SandboxSetSpec.AutoPausePolicy always takes precedence and
    is what actually reaches created Sandboxes.
    """
    pauseStrategy: PauseStrategy | None = None
    """
    PauseStrategy configures how sandboxes created from this template are
    paused when their spec.paused is true. It is only informational when a
    SandboxSet uses spec.templateRef: SandboxSetSpec.PauseStrategy always
    takes precedence and is what actually reaches created Sandboxes.
    """
    persistentContents: list[str] | None = None
    """
    PersistentContents indicates resume pod with persistent content, Enum: ip, memory, filesystem
    """
    probes: list[Probe] | None = Field(None, max_length=16)
    """
    Probes defines the named probes that sandboxes created from this template
    run while they are Running. It is only informational when a SandboxSet uses
    spec.templateRef: SandboxSetSpec.Probes always takes precedence and is what
    actually reaches created Sandboxes.
    """
    runtimes: list[Runtime] | None = None
    """
    Runtimes - Runtime configuration for sandbox object
    """
    template: V1PodTemplateSpec | None = None
    """
    Template describes the pods that will be created.
    Template is mutual exclusive with TemplateRef
    """
    volumeClaimTemplates: list[V1PersistentVolumeClaim] | None = None
    """
    VolumeClaimTemplates is a list of PVC templates to create for this Sandbox.
    """


class TcpSocket(BaseModel):
    """
    TCPSocket specifies a connection to a TCP port.
    """

    host: str | None = None
    """
    Optional: Host name to connect to, defaults to the pod IP.
    """
    port: int | str
    """
    Number or name of the port to access on the container.
    Number must be in the range 1 to 65535.
    Name must be an IANA_SVC_NAME.
    """


class TimeFormat(StrEnum):
    """
    TimeFormat indicates the format of the probe's Condition message for
    parsing as a timestamp, and defaults to "unix":

      unix     - seconds since epoch, e.g. "1787040000"
      datetime - RFC3339 with offset, e.g. "2026-08-29T08:00:00+08:00"

    NextResumeTime is set to the parsed timestamp minus LeadTime.
    """

    unix = "unix"
    datetime = "datetime"


class Type(StrEnum):
    """
    Type selects the pause mechanism.
    """

    Stop = "Stop"
    Hibernate = "Hibernate"


class WhenProbedIdleState(BaseModel):
    """
    WhenProbedIdleState pauses the sandbox when a probe's Condition message
    matches MessageRegex for at least ThresholdDuration.
    """

    messageRegex: str = Field(..., max_length=512)
    """
    MessageRegex is a regular expression matched against the probe's
    Condition message (stdout). When the message matches, the Agent is
    considered inactive. When it does not match, the Agent is considered
    active and the sandbox stays Running.
    """
    probe: str
    """
    Probe is the name of the probe to evaluate for pause decisions.
    Must match a probe name in Spec.Probes.
    """
    thresholdDuration: str
    """
    ThresholdDuration is the minimum time the probe's Condition message
    must continuously match MessageRegex before the sandbox is paused.
    Measured from the Condition's lastTransitionTime.

    It is required: pausing as soon as a single probe report matches would
    drop the smoothing this rule exists for, so there is no meaningful
    default and an unset value is a misconfiguration rather than
    "pause immediately".
    """


class WhenProbedScheduleTime(BaseModel):
    """
    WhenProbedScheduleTime resumes the sandbox before a scheduled task
    by parsing the probe's Condition message as a timestamp.
    """

    leadTime: str | None = "5m"
    """
    LeadTime is the duration before the parsed timestamp at which the
    sandbox should be resumed. For example, if the probe reports the
    next scheduled task at time T and LeadTime is 5m, the sandbox is
    resumed at T - 5m.
    """
    probe: str
    """
    Probe is the name of the probe to evaluate for resume decisions.
    Must match a probe name in Spec.Probes.
    """
    timeFormat: TimeFormat | None = "unix"
    """
    TimeFormat indicates the format of the probe's Condition message for
    parsing as a timestamp, and defaults to "unix":

      unix     - seconds since epoch, e.g. "1787040000"
      datetime - RFC3339 with offset, e.g. "2026-08-29T08:00:00+08:00"

    NextResumeTime is set to the parsed timestamp minus LeadTime.
    """
