# generated by datamodel-codegen:
#   filename:  trafficpolicy_schema.json
#   timestamp: 2026-09-03T05:22:26+00:00

from __future__ import annotations

from enum import StrEnum

from kubernetes.client.models import V1ObjectMeta
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Action(StrEnum):
    """
    Action determines whether matched traffic is allowed or denied.
    """

    allow = "allow"
    reject = "reject"


class Condition(BaseModel):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """

    lastTransitionTime: AwareDatetime
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
    """
    message: str = Field(..., max_length=32768)
    """
    message is a human readable message indicating details about the transition.
    This may be an empty string.
    """
    observedGeneration: int | None = Field(None, ge=0)
    """
    observedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str = Field(
        ...,
        max_length=1024,
        min_length=1,
        pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
    )
    """
    reason contains a programmatic identifier indicating the reason for the condition's last transition.
    Producers of specific condition types may define expected values and meanings for this field,
    and whether the values are considered a guaranteed API.
    The value should be a CamelCase string.
    This field may not be empty.
    """
    status: Status1
    """
    status of the condition, one of True, False, Unknown.
    """
    type: str = Field(
        ...,
        max_length=316,
        pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
    )
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    """


class Egress(BaseModel):
    """
    Egress defines rules applied to outbound traffic of selected pods.
    """

    rules: list[Rule] | None = Field(None, max_length=50)
    """
    Rules is the ordered rule list for this direction.
    """


class FromItem(BaseModel):
    """
    TrafficPolicyPeer identifies a traffic source or destination. Exactly one
    of CIDR, FQDN, Service, or Workload must be set.
    """

    cidr: str | None = Field(None, max_length=43, min_length=1)
    """
    CIDR is an IP address range in CIDR notation (e.g. "10.0.0.0/8").
    """
    fqdn: str | None = Field(None, max_length=253, min_length=1)
    """
    FQDN is a fully qualified domain name to match (e.g. "api.example.com").
    """
    service: Service | None = None
    """
    Service references a Kubernetes Service and its selected endpoints.
    """
    workload: Workload | None = None
    """
    Workload selects pods by namespace and labels; their IP addresses form
    the peer address set.
    """


class FromItem1(BaseModel):
    """
    TrafficPolicyPeer identifies a traffic source or destination. Exactly one
    of CIDR, FQDN, Service, or Workload must be set.
    """

    cidr: str | None = Field(None, max_length=43, min_length=1)
    """
    CIDR is an IP address range in CIDR notation (e.g. "10.0.0.0/8").
    """
    fqdn: str | None = Field(None, max_length=253, min_length=1)
    """
    FQDN is a fully qualified domain name to match (e.g. "api.example.com").
    """
    service: Service | None = None
    """
    Service references a Kubernetes Service and its selected endpoints.
    """
    workload: Workload | None = None
    """
    Workload selects pods by namespace and labels; their IP addresses form
    the peer address set.
    """


class Ingress(BaseModel):
    """
    Ingress defines rules applied to inbound traffic of selected pods.
    """

    rules: list[Rule1] | None = Field(None, max_length=50)
    """
    Rules is the ordered rule list for this direction.
    """


class MatchExpression(BaseModel):
    """
    A label selector requirement is a selector that contains values, a key, and an operator that
    relates the key and values.
    """

    key: str
    """
    key is the label key that the selector applies to.
    """
    operator: str
    """
    operator represents a key's relationship to a set of values.
    Valid operators are In, NotIn, Exists and DoesNotExist.
    """
    values: list[str] | None = None
    """
    values is an array of string values. If the operator is In or NotIn,
    the values array must be non-empty. If the operator is Exists or DoesNotExist,
    the values array must be empty. This array is replaced during a strategic
    merge patch.
    """


class Port(BaseModel):
    """
    TrafficPolicyPort restricts a rule to specific protocol/port combinations.
    If Protocol is non-empty and Port is nil, matches all ports of that protocol.
    """

    endPort: int | None = Field(None, ge=1, le=65535)
    """
    EndPort defines the upper bound of a port range (inclusive). When set,
    the rule matches destination ports from Port to EndPort. Requires Port
    to be set and must be >= Port.
    """
    port: int | None = Field(None, ge=1, le=65535)
    """
    Port is the destination port number. When nil, the rule applies to all
    TCP ports.
    """
    protocol: Protocol | None = None


class Port1(BaseModel):
    """
    TrafficPolicyPort restricts a rule to specific protocol/port combinations.
    If Protocol is non-empty and Port is nil, matches all ports of that protocol.
    """

    endPort: int | None = Field(None, ge=1, le=65535)
    """
    EndPort defines the upper bound of a port range (inclusive). When set,
    the rule matches destination ports from Port to EndPort. Requires Port
    to be set and must be >= Port.
    """
    port: int | None = Field(None, ge=1, le=65535)
    """
    Port is the destination port number. When nil, the rule applies to all
    TCP ports.
    """
    protocol: Protocol | None = None


class Protocol(StrEnum):
    TCP = "TCP"
    UDP = "UDP"
    ICMP = "ICMP"
    SCTP = "SCTP"


class Rule(BaseModel):
    """
    TrafficPolicyRule is one entry in the ordered rule list. Each rule
    specifies an action (allow/reject) and optional peer and port constraints.
    When From/To/Ports are all empty, the action applies to all traffic in
    that direction.
    """

    action: Action
    """
    Action determines whether matched traffic is allowed or denied.
    """
    from_: list[FromItem] | None = Field(None, alias="from", max_length=20)
    """
    From lists source peers. Multiple entries are ORed.
    """
    ports: list[Port] | None = Field(None, max_length=20)
    """
    Ports restricts this rule to specific L4 protocol/port combinations.
    Multiple entries are ORed. If empty, the rule matches all ports.
    """
    to: list[ToItem] | None = Field(None, max_length=20)
    """
    To lists destination peers. Multiple entries are ORed.
    """


class Rule1(BaseModel):
    """
    TrafficPolicyRule is one entry in the ordered rule list. Each rule
    specifies an action (allow/reject) and optional peer and port constraints.
    When From/To/Ports are all empty, the action applies to all traffic in
    that direction.
    """

    action: Action
    """
    Action determines whether matched traffic is allowed or denied.
    """
    from_: list[FromItem1] | None = Field(None, alias="from", max_length=20)
    """
    From lists source peers. Multiple entries are ORed.
    """
    ports: list[Port1] | None = Field(None, max_length=20)
    """
    Ports restricts this rule to specific L4 protocol/port combinations.
    Multiple entries are ORed. If empty, the rule matches all ports.
    """
    to: list[ToItem1] | None = Field(None, max_length=20)
    """
    To lists destination peers. Multiple entries are ORed.
    """


class Selector(BaseModel):
    """
    Selector chooses the pods this policy applies to. Standard
    LabelSelector semantics: an EMPTY selector matches EVERY pod within
    the policy's scope (namespace for TrafficPolicy, cluster-wide for
    GlobalTrafficPolicy).
    """

    matchExpressions: list[MatchExpression] | None = None
    """
    matchExpressions is a list of label selector requirements. The requirements are ANDed.
    """
    matchLabels: dict[str, str] | None = None
    """
    matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
    map is equivalent to an element of matchExpressions, whose key field is "key", the
    operator is "In", and the values array contains only "value". The requirements are ANDed.
    """


class Service(BaseModel):
    """
    Service references a Kubernetes Service and its selected endpoints.
    """

    name: str = Field(..., max_length=253, min_length=1)
    """
    Name is the Service resource name.
    """
    namespace: str | None = Field(None, max_length=63, min_length=1)
    """
    Namespace is the namespace of the target Service. When omitted, defaults
    to the namespace of the enclosing TrafficPolicy.
    """


class Spec(BaseModel):
    """
    TrafficPolicySpec defines bidirectional policy state on selected pods.
    """

    egress: Egress | None = None
    """
    Egress defines rules applied to outbound traffic of selected pods.
    """
    ingress: Ingress | None = None
    """
    Ingress defines rules applied to inbound traffic of selected pods.
    """
    priority: int | None = Field(1000, ge=0)
    """
    Priority determines the evaluation order when multiple TrafficPolicies
    match the same pod. Higher values are evaluated first. When two
    policies share the same priority, the result is implementation-defined.
    """
    selector: Selector
    """
    Selector chooses the pods this policy applies to. Standard
    LabelSelector semantics: an EMPTY selector matches EVERY pod within
    the policy's scope (namespace for TrafficPolicy, cluster-wide for
    GlobalTrafficPolicy).
    """


class Status(BaseModel):
    """
    TrafficPolicyStatus captures the observed state of TrafficPolicy.
    """

    conditions: list[Condition] | None = Field(None, max_length=20)
    """
    Conditions summarises the policy's current state. Standard types are
    Accepted and Programmed (see TrafficPolicyCondition* constants).
    """


class Status1(StrEnum):
    """
    status of the condition, one of True, False, Unknown.
    """

    True_ = "True"
    False_ = "False"
    Unknown = "Unknown"


class ToItem(BaseModel):
    """
    TrafficPolicyPeer identifies a traffic source or destination. Exactly one
    of CIDR, FQDN, Service, or Workload must be set.
    """

    cidr: str | None = Field(None, max_length=43, min_length=1)
    """
    CIDR is an IP address range in CIDR notation (e.g. "10.0.0.0/8").
    """
    fqdn: str | None = Field(None, max_length=253, min_length=1)
    """
    FQDN is a fully qualified domain name to match (e.g. "api.example.com").
    """
    service: Service | None = None
    """
    Service references a Kubernetes Service and its selected endpoints.
    """
    workload: Workload | None = None
    """
    Workload selects pods by namespace and labels; their IP addresses form
    the peer address set.
    """


class ToItem1(BaseModel):
    """
    TrafficPolicyPeer identifies a traffic source or destination. Exactly one
    of CIDR, FQDN, Service, or Workload must be set.
    """

    cidr: str | None = Field(None, max_length=43, min_length=1)
    """
    CIDR is an IP address range in CIDR notation (e.g. "10.0.0.0/8").
    """
    fqdn: str | None = Field(None, max_length=253, min_length=1)
    """
    FQDN is a fully qualified domain name to match (e.g. "api.example.com").
    """
    service: Service | None = None
    """
    Service references a Kubernetes Service and its selected endpoints.
    """
    workload: Workload | None = None
    """
    Workload selects pods by namespace and labels; their IP addresses form
    the peer address set.
    """


class TrafficPolicy(BaseModel):
    """
    TrafficPolicy defines bidirectional traffic rules for selected pods.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec | None = None
    """
    TrafficPolicySpec defines bidirectional policy state on selected pods.
    """
    status: Status | None = None
    """
    TrafficPolicyStatus captures the observed state of TrafficPolicy.
    """


class Workload(BaseModel):
    """
    Workload selects pods by namespace and labels; their IP addresses form
    the peer address set.
    """

    namespace: str = Field(..., max_length=63, min_length=1)
    """
    Namespace of the target pods.
    """
    selector: dict[str, str] = Field(..., max_length=10)
    """
    Selector is a label selector that matches the target pods.
    """
