/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openkruise/agents-api/client/clientset/versioned/typed/agents/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAgentsV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAgentsV1alpha1) Checkpoints(namespace string) v1alpha1.CheckpointInterface {
	return newFakeCheckpoints(c, namespace)
}

func (c *FakeAgentsV1alpha1) Commits(namespace string) v1alpha1.CommitInterface {
	return newFakeCommits(c, namespace)
}

func (c *FakeAgentsV1alpha1) GlobalSecurityProfiles() v1alpha1.GlobalSecurityProfileInterface {
	return newFakeGlobalSecurityProfiles(c)
}

func (c *FakeAgentsV1alpha1) GlobalTrafficPolicies() v1alpha1.GlobalTrafficPolicyInterface {
	return newFakeGlobalTrafficPolicies(c)
}

func (c *FakeAgentsV1alpha1) PoolAutoscalers(namespace string) v1alpha1.PoolAutoscalerInterface {
	return newFakePoolAutoscalers(c, namespace)
}

func (c *FakeAgentsV1alpha1) Sandboxes(namespace string) v1alpha1.SandboxInterface {
	return newFakeSandboxes(c, namespace)
}

func (c *FakeAgentsV1alpha1) SandboxClaims(namespace string) v1alpha1.SandboxClaimInterface {
	return newFakeSandboxClaims(c, namespace)
}

func (c *FakeAgentsV1alpha1) SandboxSets(namespace string) v1alpha1.SandboxSetInterface {
	return newFakeSandboxSets(c, namespace)
}

func (c *FakeAgentsV1alpha1) SandboxTemplates(namespace string) v1alpha1.SandboxTemplateInterface {
	return newFakeSandboxTemplates(c, namespace)
}

func (c *FakeAgentsV1alpha1) SandboxUpdateOps(namespace string) v1alpha1.SandboxUpdateOpsInterface {
	return newFakeSandboxUpdateOps(c, namespace)
}

func (c *FakeAgentsV1alpha1) SecurityProfiles(namespace string) v1alpha1.SecurityProfileInterface {
	return newFakeSecurityProfiles(c, namespace)
}

func (c *FakeAgentsV1alpha1) TrafficPolicies(namespace string) v1alpha1.TrafficPolicyInterface {
	return newFakeTrafficPolicies(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAgentsV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
