/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/openkruise/agents-api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Checkpoints returns a CheckpointInformer.
	Checkpoints() CheckpointInformer
	// Commits returns a CommitInformer.
	Commits() CommitInformer
	// GlobalSecurityProfiles returns a GlobalSecurityProfileInformer.
	GlobalSecurityProfiles() GlobalSecurityProfileInformer
	// GlobalTrafficPolicies returns a GlobalTrafficPolicyInformer.
	GlobalTrafficPolicies() GlobalTrafficPolicyInformer
	// PoolAutoscalers returns a PoolAutoscalerInformer.
	PoolAutoscalers() PoolAutoscalerInformer
	// Sandboxes returns a SandboxInformer.
	Sandboxes() SandboxInformer
	// SandboxClaims returns a SandboxClaimInformer.
	SandboxClaims() SandboxClaimInformer
	// SandboxSets returns a SandboxSetInformer.
	SandboxSets() SandboxSetInformer
	// SandboxTemplates returns a SandboxTemplateInformer.
	SandboxTemplates() SandboxTemplateInformer
	// SandboxUpdateOps returns a SandboxUpdateOpsInformer.
	SandboxUpdateOps() SandboxUpdateOpsInformer
	// SecurityProfiles returns a SecurityProfileInformer.
	SecurityProfiles() SecurityProfileInformer
	// TrafficPolicies returns a TrafficPolicyInformer.
	TrafficPolicies() TrafficPolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Checkpoints returns a CheckpointInformer.
func (v *version) Checkpoints() CheckpointInformer {
	return &checkpointInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Commits returns a CommitInformer.
func (v *version) Commits() CommitInformer {
	return &commitInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GlobalSecurityProfiles returns a GlobalSecurityProfileInformer.
func (v *version) GlobalSecurityProfiles() GlobalSecurityProfileInformer {
	return &globalSecurityProfileInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GlobalTrafficPolicies returns a GlobalTrafficPolicyInformer.
func (v *version) GlobalTrafficPolicies() GlobalTrafficPolicyInformer {
	return &globalTrafficPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// PoolAutoscalers returns a PoolAutoscalerInformer.
func (v *version) PoolAutoscalers() PoolAutoscalerInformer {
	return &poolAutoscalerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Sandboxes returns a SandboxInformer.
func (v *version) Sandboxes() SandboxInformer {
	return &sandboxInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SandboxClaims returns a SandboxClaimInformer.
func (v *version) SandboxClaims() SandboxClaimInformer {
	return &sandboxClaimInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SandboxSets returns a SandboxSetInformer.
func (v *version) SandboxSets() SandboxSetInformer {
	return &sandboxSetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SandboxTemplates returns a SandboxTemplateInformer.
func (v *version) SandboxTemplates() SandboxTemplateInformer {
	return &sandboxTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SandboxUpdateOps returns a SandboxUpdateOpsInformer.
func (v *version) SandboxUpdateOps() SandboxUpdateOpsInformer {
	return &sandboxUpdateOpsInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SecurityProfiles returns a SecurityProfileInformer.
func (v *version) SecurityProfiles() SecurityProfileInformer {
	return &securityProfileInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TrafficPolicies returns a TrafficPolicyInformer.
func (v *version) TrafficPolicies() TrafficPolicyInformer {
	return &trafficPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
