/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	agentsapiagentsv1alpha1 "github.com/openkruise/agents-api/agents/v1alpha1"
	versioned "github.com/openkruise/agents-api/client/clientset/versioned"
	internalinterfaces "github.com/openkruise/agents-api/client/informers/externalversions/internalinterfaces"
	agentsv1alpha1 "github.com/openkruise/agents-api/client/listers/agents/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PoolAutoscalerInformer provides access to a shared informer and lister for
// PoolAutoscalers.
type PoolAutoscalerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() agentsv1alpha1.PoolAutoscalerLister
}

type poolAutoscalerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPoolAutoscalerInformer constructs a new informer for PoolAutoscaler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPoolAutoscalerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPoolAutoscalerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPoolAutoscalerInformer constructs a new informer for PoolAutoscaler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPoolAutoscalerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1alpha1().PoolAutoscalers(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1alpha1().PoolAutoscalers(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1alpha1().PoolAutoscalers(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1alpha1().PoolAutoscalers(namespace).Watch(ctx, options)
			},
		}, client),
		&agentsapiagentsv1alpha1.PoolAutoscaler{},
		resyncPeriod,
		indexers,
	)
}

func (f *poolAutoscalerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPoolAutoscalerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *poolAutoscalerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&agentsapiagentsv1alpha1.PoolAutoscaler{}, f.defaultInformer)
}

func (f *poolAutoscalerInformer) Lister() agentsv1alpha1.PoolAutoscalerLister {
	return agentsv1alpha1.NewPoolAutoscalerLister(f.Informer().GetIndexer())
}
