/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CheckpointListerExpansion allows custom methods to be added to
// CheckpointLister.
type CheckpointListerExpansion interface{}

// CheckpointNamespaceListerExpansion allows custom methods to be added to
// CheckpointNamespaceLister.
type CheckpointNamespaceListerExpansion interface{}

// CommitListerExpansion allows custom methods to be added to
// CommitLister.
type CommitListerExpansion interface{}

// CommitNamespaceListerExpansion allows custom methods to be added to
// CommitNamespaceLister.
type CommitNamespaceListerExpansion interface{}

// GlobalSecurityProfileListerExpansion allows custom methods to be added to
// GlobalSecurityProfileLister.
type GlobalSecurityProfileListerExpansion interface{}

// GlobalTrafficPolicyListerExpansion allows custom methods to be added to
// GlobalTrafficPolicyLister.
type GlobalTrafficPolicyListerExpansion interface{}

// PoolAutoscalerListerExpansion allows custom methods to be added to
// PoolAutoscalerLister.
type PoolAutoscalerListerExpansion interface{}

// PoolAutoscalerNamespaceListerExpansion allows custom methods to be added to
// PoolAutoscalerNamespaceLister.
type PoolAutoscalerNamespaceListerExpansion interface{}

// SandboxListerExpansion allows custom methods to be added to
// SandboxLister.
type SandboxListerExpansion interface{}

// SandboxNamespaceListerExpansion allows custom methods to be added to
// SandboxNamespaceLister.
type SandboxNamespaceListerExpansion interface{}

// SandboxClaimListerExpansion allows custom methods to be added to
// SandboxClaimLister.
type SandboxClaimListerExpansion interface{}

// SandboxClaimNamespaceListerExpansion allows custom methods to be added to
// SandboxClaimNamespaceLister.
type SandboxClaimNamespaceListerExpansion interface{}

// SandboxSetListerExpansion allows custom methods to be added to
// SandboxSetLister.
type SandboxSetListerExpansion interface{}

// SandboxSetNamespaceListerExpansion allows custom methods to be added to
// SandboxSetNamespaceLister.
type SandboxSetNamespaceListerExpansion interface{}

// SandboxTemplateListerExpansion allows custom methods to be added to
// SandboxTemplateLister.
type SandboxTemplateListerExpansion interface{}

// SandboxTemplateNamespaceListerExpansion allows custom methods to be added to
// SandboxTemplateNamespaceLister.
type SandboxTemplateNamespaceListerExpansion interface{}

// SandboxUpdateOpsListerExpansion allows custom methods to be added to
// SandboxUpdateOpsLister.
type SandboxUpdateOpsListerExpansion interface{}

// SandboxUpdateOpsNamespaceListerExpansion allows custom methods to be added to
// SandboxUpdateOpsNamespaceLister.
type SandboxUpdateOpsNamespaceListerExpansion interface{}

// SecurityProfileListerExpansion allows custom methods to be added to
// SecurityProfileLister.
type SecurityProfileListerExpansion interface{}

// SecurityProfileNamespaceListerExpansion allows custom methods to be added to
// SecurityProfileNamespaceLister.
type SecurityProfileNamespaceListerExpansion interface{}

// TrafficPolicyListerExpansion allows custom methods to be added to
// TrafficPolicyLister.
type TrafficPolicyListerExpansion interface{}

// TrafficPolicyNamespaceListerExpansion allows custom methods to be added to
// TrafficPolicyNamespaceLister.
type TrafficPolicyNamespaceListerExpansion interface{}
