/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	agentsv1alpha1 "github.com/openkruise/agents-api/agents/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PoolAutoscalerLister helps list PoolAutoscalers.
// All objects returned here must be treated as read-only.
type PoolAutoscalerLister interface {
	// List lists all PoolAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentsv1alpha1.PoolAutoscaler, err error)
	// PoolAutoscalers returns an object that can list and get PoolAutoscalers.
	PoolAutoscalers(namespace string) PoolAutoscalerNamespaceLister
	PoolAutoscalerListerExpansion
}

// poolAutoscalerLister implements the PoolAutoscalerLister interface.
type poolAutoscalerLister struct {
	listers.ResourceIndexer[*agentsv1alpha1.PoolAutoscaler]
}

// NewPoolAutoscalerLister returns a new PoolAutoscalerLister.
func NewPoolAutoscalerLister(indexer cache.Indexer) PoolAutoscalerLister {
	return &poolAutoscalerLister{listers.New[*agentsv1alpha1.PoolAutoscaler](indexer, agentsv1alpha1.Resource("poolautoscaler"))}
}

// PoolAutoscalers returns an object that can list and get PoolAutoscalers.
func (s *poolAutoscalerLister) PoolAutoscalers(namespace string) PoolAutoscalerNamespaceLister {
	return poolAutoscalerNamespaceLister{listers.NewNamespaced[*agentsv1alpha1.PoolAutoscaler](s.ResourceIndexer, namespace)}
}

// PoolAutoscalerNamespaceLister helps list and get PoolAutoscalers.
// All objects returned here must be treated as read-only.
type PoolAutoscalerNamespaceLister interface {
	// List lists all PoolAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentsv1alpha1.PoolAutoscaler, err error)
	// Get retrieves the PoolAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agentsv1alpha1.PoolAutoscaler, error)
	PoolAutoscalerNamespaceListerExpansion
}

// poolAutoscalerNamespaceLister implements the PoolAutoscalerNamespaceLister
// interface.
type poolAutoscalerNamespaceLister struct {
	listers.ResourceIndexer[*agentsv1alpha1.PoolAutoscaler]
}
